AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  NetworkStackParameter:
    Type: String
    Default: network
    Description: Network stack to deploy into.
  SecurityGroupStackParameter:
    Type: String
    Default: security-groups
    Description: Security group definitions.
  
Resources:

  # Hardware aquisition
  JenkinsMasterLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: JenkinsMasterLaunchTemplate
      LaunchTemplateData: 
        ImageId: ami-0e1a69c81175d6bf2
        InstanceType: t2.micro
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            MaxPrice: "0.005"

  # Configuration and installation definition
  JenkinsMaster:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          Install:
            - "InstallDocker"
            - "PullJenkinsImage"
            - "StartJenkinsContainer"
        InstallDocker:
          packages:
            yum:
              docker: []
          services:
            sysvinit:
              docker:
                enabled: "true"
                ensureRunning: "true"
                packages:
                  yum:
                    - "docker"
        PullJenkinsImage:
          commands:
            test:
              command: "docker pull jenkins/jenkins:lts"
        StartJenkinsContainer:
          commands:
            test:
              command: "docker run -d -p 80:8080 jenkins/jenkins:lts"
    Properties:
      SubnetId: 
        Fn::ImportValue: !Sub "${NetworkStackParameter}-Subnet1"
      LaunchTemplate:
        LaunchTemplateId:
          Ref: JenkinsMasterLaunchTemplate
        Version: '1'
      SecurityGroupIds:
      - Fn::ImportValue: !Sub "${SecurityGroupStackParameter}-SecurityGroupSSH"
      - Fn::ImportValue: !Sub "${SecurityGroupStackParameter}-SecurityGroupWebServer"
      KeyName: ssh-laptop
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          
          yum install -y aws-cfn-bootstrap

          /opt/aws/bin/cfn-init -v \
            --stack ${ AWS::StackName } \
            --resource JenkinsMaster \
            --configsets Install \
            --region ${ AWS::Region }

  # Load balancer as http termination point
  JenkinsLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: 
        - Fn::ImportValue: !Sub "${NetworkStackParameter}-Subnet1"
        - Fn::ImportValue: !Sub "${NetworkStackParameter}-Subnet2"
      SecurityGroups:
      - Fn::ImportValue: !Sub "${SecurityGroupStackParameter}-SecurityGroupWebServer"

  # Redirect http to https
  JenkinsLoadBalancerHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref JenkinsLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Host: '#{host}'
            Path: '/#{path}'
            Port: '443'
            Protocol: HTTPS
            StatusCode: HTTP_301

  # Forward https traffic to jenkins http endpoint
  JenkinsLoadBalancerHTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref JenkinsLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:ap-southeast-2:365033114011:certificate/cb73021b-6107-47ec-8f0e-dc02dcb6ec25
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref JenkinsMasterTargetGroup

  # Definition of jenkins http endpoint for load balancer
  JenkinsMasterTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      TargetType: ip
      Targets:
        - Id: !GetAtt JenkinsMaster.PrivateIp
          Port: 80
      VpcId: 
        Fn::ImportValue: !Sub "${NetworkStackParameter}-VPC"
      HealthCheckPath: /login

  # DNS record for jenkins.morleystuff.com
  JenkinsRecordSetGroup:
    Type: 'AWS::Route53::RecordSetGroup'
    DependsOn:
      - JenkinsMasterLaunchTemplate
    Properties:
      HostedZoneId: ZT0O09PTBTJOV
      RecordSets:
        - Name: jenkins.morleystuff.com
          Type: A
          AliasTarget:
            DNSName: !GetAtt JenkinsLoadBalancer.DNSName
            HostedZoneId: !GetAtt JenkinsLoadBalancer.CanonicalHostedZoneID
