AWSTemplateFormatVersion: "2010-09-09"

Resources:

  SshAccessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Jenkins master instance (ssh & web traffic)
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  JenkinsMasterLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: JenkinsMasterLaunchTemplate
      LaunchTemplateData: 
        ImageId: ami-0e1a69c81175d6bf2
        InstanceType: t2.micro
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            MaxPrice: "0.005"

  JenkinsMaster:
    Type: AWS::EC2::Instance
    DependsOn:
      - JenkinsMasterLaunchTemplate
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          Install:
            - "InstallDocker"
            - "PullJenkinsImage"
            - "StartJenkinsContainer"
        InstallDocker:
          packages:
            yum:
              docker: []
          services:
            sysvinit:
              docker:
                enabled: "true"
                ensureRunning: "true"
                packages:
                  yum:
                    - "docker"
        PullJenkinsImage:
          commands:
            test:
              command: "docker pull jenkins/jenkins:lts"
        StartJenkinsContainer:
          commands:
            test:
              command: "docker run -d -p 80:8080 jenkins/jenkins:lts"
    Properties:
      LaunchTemplate:
        LaunchTemplateId:
          Ref: JenkinsMasterLaunchTemplate
        Version: 1
      SecurityGroupIds: [!Ref SshAccessSecurityGroup]
      KeyName: ssh-laptop
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          
          yum install -y aws-cfn-bootstrap

          /opt/aws/bin/cfn-init -v \
            --stack ${ AWS::StackName } \
            --resource JenkinsMaster \
            --configsets Install \
            --region ${ AWS::Region }

  JenkinsRecordSetGroup:
    Type: 'AWS::Route53::RecordSetGroup'
    DependsOn:
      - JenkinsMasterLaunchTemplate
    Properties:
      HostedZoneId: ZT0O09PTBTJOV
      RecordSets:
        - Name: jenkins.morleystuff.com
          Type: A
          TTL: '900'
          ResourceRecords:
            - !GetAtt JenkinsMaster.PublicIp
  
  

