AWSTemplateFormatVersion: "2010-09-09"

Resources:

  InfrastructureVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/24'

  InfrastructureSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref InfrastructureVPC
      CidrBlock: '10.0.0.0/26'
      AvailabilityZone: ap-southeast-2a
      MapPublicIpOnLaunch: true

  InfrastructureSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref InfrastructureVPC
      CidrBlock: '10.0.0.128/26'
      AvailabilityZone: ap-southeast-2b
      MapPublicIpOnLaunch: true

  InfrastructureInternetGateway:
    Type: AWS::EC2::InternetGateway

  InfrastructureInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InfrastructureInternetGateway
      VpcId: !Ref InfrastructureVPC

  InfrastructureNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref InfrastructureVPC

  InfrastructureNaclAllowSSH:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref InfrastructureNetworkAcl
      Protocol: 6
      RuleAction: allow
      RuleNumber: 100
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 22
        To: 22

  InfrastructureNaclAllowHTTP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref InfrastructureNetworkAcl
      Protocol: 6
      RuleAction: allow
      RuleNumber: 101
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 80
        To: 80

  InfrastructureNaclAllowReturnHTTP:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref InfrastructureNetworkAcl
      Protocol: 6
      RuleAction: allow
      RuleNumber: 102
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 1024
        To: 65535

  InfrastructureNaclAllowHTTPS:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref InfrastructureNetworkAcl
      Protocol: 6
      RuleAction: allow
      RuleNumber: 103
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: 443
        To: 443

  InfrastructureNaclAllowOutbound:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref InfrastructureNetworkAcl
      Protocol: -1
      RuleAction: allow
      RuleNumber: 100
      Egress: true
      CidrBlock: 0.0.0.0/0

  InfrastructureSubnet1NaclAssociation:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      NetworkAclId: !Ref InfrastructureNetworkAcl
      SubnetId: !Ref InfrastructureSubnet1

  InfrastructureSubnet2NaclAssociation:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      NetworkAclId: !Ref InfrastructureNetworkAcl
      SubnetId: !Ref InfrastructureSubnet2

  InfrastructureRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref InfrastructureVPC

  InfrastructureSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref InfrastructureRouteTable
      SubnetId: !Ref InfrastructureSubnet1

  InfrastructureSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref InfrastructureRouteTable
      SubnetId: !Ref InfrastructureSubnet2

  InfrastructureInternetGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref InfrastructureRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InfrastructureInternetGateway

  JenkinsMasterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Jenkins master instance (ssh & web traffic)
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      VpcId: !Ref InfrastructureVPC

  JenkinsMasterLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Jenkins master load balancer
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      VpcId: !Ref InfrastructureVPC

  JenkinsMasterLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: JenkinsMasterLaunchTemplate
      LaunchTemplateData: 
        ImageId: ami-0e1a69c81175d6bf2
        InstanceType: t2.micro
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            MaxPrice: "0.005"

  JenkinsMaster:
    Type: AWS::EC2::Instance
    DependsOn:
      - JenkinsMasterLaunchTemplate
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          Install:
            - "InstallDocker"
            - "PullJenkinsImage"
            - "StartJenkinsContainer"
        InstallDocker:
          packages:
            yum:
              docker: []
          services:
            sysvinit:
              docker:
                enabled: "true"
                ensureRunning: "true"
                packages:
                  yum:
                    - "docker"
        PullJenkinsImage:
          commands:
            test:
              command: "docker pull jenkins/jenkins:lts"
        StartJenkinsContainer:
          commands:
            test:
              command: "docker run -d -p 80:8080 jenkins/jenkins:lts"
    Properties:
      SubnetId: !Ref InfrastructureSubnet1
      LaunchTemplate:
        LaunchTemplateId:
          Ref: JenkinsMasterLaunchTemplate
        Version: 1
      SecurityGroupIds: [!Ref JenkinsMasterSecurityGroup]
      KeyName: ssh-laptop
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          
          yum install -y aws-cfn-bootstrap

          /opt/aws/bin/cfn-init -v \
            --stack ${ AWS::StackName } \
            --resource JenkinsMaster \
            --configsets Install \
            --region ${ AWS::Region }

  JenkinsLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: [!Ref InfrastructureSubnet1, !Ref InfrastructureSubnet2]
      SecurityGroups:
        - !Ref JenkinsMasterLoadBalancerSecurityGroup

  JenkinsLoadBalancerHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref JenkinsLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Host: '#{host}'
            Path: '/#{path}'
            Port: 443
            Protocol: HTTPS
            StatusCode: HTTP_301

  JenkinsLoadBalancerHTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref JenkinsLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:ap-southeast-2:365033114011:certificate/cb73021b-6107-47ec-8f0e-dc02dcb6ec25
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref JenkinsMasterTargetGroup

  JenkinsMasterTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      TargetType: ip
      Targets:
        - Id: !GetAtt JenkinsMaster.PrivateIp
          Port: 80
      VpcId: !Ref InfrastructureVPC
      HealthCheckPath: /login

  JenkinsRecordSetGroup:
    Type: 'AWS::Route53::RecordSetGroup'
    DependsOn:
      - JenkinsMasterLaunchTemplate
    Properties:
      HostedZoneId: ZT0O09PTBTJOV
      RecordSets:
        - Name: jenkins.morleystuff.com
          Type: A
          AliasTarget:
            DNSName: !GetAtt JenkinsLoadBalancer.DNSName
            HostedZoneId: !GetAtt JenkinsLoadBalancer.CanonicalHostedZoneID
